routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(array('prefix'=>'admin','middleware' => ['auth']), function ()
{
    Route::get('/', 'CategoryController@index');
    Route::get('/product/{id}/deactivate','ProductController@deactivate')->name('product.deactivate');
    Route::get('/product/{id}/activate','ProductController@activate')->name('product.activate');
    Route::resource('category','CategoryController');
    Route::resource('product','ProductController');

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    // public $table = 'products';

    protected $fillable = [
        'name', 'category_id', 'description', 'original_price','discount_price','image_name','isAvailable',
    ];

    public function category()
    {
        return $this->belongsTo('App\Category','id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\Product;
use App\Category;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //

        $products= DB::table('products')->join('categories', 'products.category_id', '=', 'categories.id')
            ->select('products.*','categories.category_name')
           ->get();

//        $enterprises= serialize($enterprisesObject);
        return view('product.product',compact('products'))
            ->with('i', (request()->input('page', 1) - 1) * 5);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::all();
        return view('product.add_product',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        request()->validate([
            'product_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'name' => 'required|string|unique:Products',
            'original_price' => 'required',
            'category_id'   =>  'required',
        ]);
        
        $imageName;
        if ($request->hasFile('product_image')) {
            $image = $request->file('product_image');
            $imageName = $image->getClientOriginalName();
            $destinationPath = public_path('/images/products');
            $image->move($destinationPath, $imageName);
    
        }
        
        product::create([
            'name'=>$request->input('name'),
            'image_name' =>$imageName,
            'original_price' =>$request->input('original_price'),
            'discount_price' => $request->input('discount_price'),
            'description'=>$request->input('description'),
            'category_id'=> $request->input('category_id'),
            'isAvailable'=> true,
        ]);
        
        return redirect()->route('product.index')
            ->with('success', 'Product created successfully');

        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        // $product = Product::find($id);
//        return "hello";

        // return view('enterprise.reserve-msg', compact('enterprise', $enterprise))->with('status', 'Reserve Enterprise');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // request()->validate([
        //     //            'EnterpriseName' => 'required|string|unique:EnterpriseAccount',
        //                 'EnterpriseContactnumber' => 'required',
        //                 'EnterpriseEmail' => 'required|email',
        //                 'EnterpriseAddress' => 'required',
        //             ]);
            
        //             enterpriseaccount::find($id)->update($request->all());
            
        //             return redirect()->route('enterprise.index')
        //                 ->with('success', 'Article updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function deactivate($id)
    {
        Product::find($id)->update(['isAvailable'=> false]);
            
        return redirect()->route('product.index')
        ->with('success', 'Product '.$id .' Deactivated successfully');
       
    }

    public function activate($id)
    {
        Product::find($id)->update(['isAvailable'=> true]);
            
        return redirect()->route('product.index')
        ->with('success', 'Product '.$id .' Activated successfully');
       
    }

    public function getProducts()
    {
        // $userId=User::where('EnterpriseId',$id)->first()->id;

        $products = Product::where('isAvailable',true)
                    ->orderBy('created_at', 'desc')
                    ->get();

        // >orderBy('name', 'desc')
        //        ->take(10)
        //        ->get();

        return response()->json($products, 200);
       
    }

    // private function imageUpload($file)
    // {
    //     if ($request->hasFile('input_img')) {
    //         if($request->file('input_img')->isValid()) {
    //             try {
    //                 $file = $request->file('input_img');
    //                 $name = rand(11111, 99999) . '.' . $file->getClientOriginalExtension();
        
    //                 # save to DB
    //                 $tickes = Users::create(['imagePath' => 'storage/'.$name]);
        
    //                 $request->file('input_img')->move("storage", $name);

    //             } catch (Illuminate\Filesystem\FileNotFoundException $e) {
        
    //             }
    //         }
    //     }
    // }

    // public function fileUpload(Request $request) {

    //     $this->validate($request, [
    //         'product_image' => 'required|image|mimes:jpeg,png,jpg|max:2048',
    //     ]);
    
    //     if ($request->hasFile('product_image')) {
    //         $image = $request->file('input_img');
    //         $name = $image->getClientOriginalName().'.'.$image->getClientOriginalExtension();
    //         $destinationPath = public_path('/images');
    //         $image->move($destinationPath, $name);
    //         $this->save();
    
    //         return back()->with('success','Image Upload successfully');
    //     }
    // }
}

resources/views/product/add_product.blade.php
@extends('layouts.admin_layout')
@section('content')

    <section class="content-header">
        <h1>
            Add Product
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>

    <!-- Main content -->
    <section style="background-color:white" class="content container-fluid">

<div class="row">
            
<form class="form-horizontal" method="POST" enctype="multipart/form-data" action="{{ route('product.store')}}">
                {{ csrf_field() }}
                <div class="modal-body form">

                    <div class="form-body">

                        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Product Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" required autofocus>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="category_name" class="col-md-4 control-label">Original Price</label>

                            <div class="col-md-6">
                                <select id="category_id" name="category_id" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="dropdown">
                                    @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ $category->category_name }}</option>
                                    @endforeach
                                    </select>
                            </div>

                        </div>

                        <div class="form-group{{ $errors->has('original_price') ? ' has-error' : '' }}">
                            <label for="original_price" class="col-md-4 control-label">Original Price</label>

                            <div class="col-md-6">
                                <input id="original_price" type="number" class="form-control" name="original_price" value="{{ old('original_price') }}" required autofocus>

                                @if ($errors->has('original_price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('original_price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('discount_price') ? ' has-error' : '' }}">
                            <label for="discount_price" class="col-md-4 control-label">Discount Price</label>

                            <div class="col-md-6">
                                <input id="discount_price" type="number" class="form-control" name="discount_price" value="{{ old('discount_price') }}" autofocus>

                                @if ($errors->has('discount_price'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('discount_price') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Description</label>

                            <div class="col-md-6">
                                <textarea id="description" type="text" class="form-control" name="description" value="{{ old('description') }}" autofocus></textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('product_image') ? ' has-error' : '' }}">
                            <label for="product_image" class="col-md-4 control-label">Image</label>

                            <div class="col-md-6">
                                <input type="file" id="product_image" name="product_image" class="form-control" value="{{ old('product_image') }}" autofocus>

                                @if ($errors->has('product_image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('product_image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                    </div>

                </div>
                <div class="modal-footer">


                    <button type="submit"  class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </form>

</div>
    </section>
@endsection

resources/views/product/edit_product.blade.php
@extends('admin_layout')
@section('content')

    <section class="content-header">
        <h1>
            Edit Product
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>

    <!-- Main content -->
    <section style="background-color:white" class="content container-fluid">

<div class="row">
            <div class="modal-header">
                {{--<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>--}}
                {{-- <h3 class="modal-title">Enterprise Form</h3>--}}
            </div>
<form  class="form-horizontal" method="POST" action="{{ route('enterprise.update',$enterprise->EnterpriseId) }}">
    <input type="hidden" name="_method" value="PUT">
    {{ csrf_field() }}
    <div class="modal-body edit-content form">


        <div class="form-body">

            <div class="form-group{{ $errors->has('EnterpriseName') ? ' has-error' : '' }}">
                <label for="EnterpriseName" class="col-md-2 control-label">Company Name</label>

                <div class="col-md-6">
                    <label  id="EnterpriseName" type="text" class="form-control" name="EnterpriseName">{{$enterprise->EnterpriseName}}</label>

                    @if ($errors->has('EnterpriseName'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseName') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('EnterpriseContactnumber') ? ' has-error' : '' }}">
                <label for="EnterpriseName" class="col-md-2 control-label">Contact Number</label>

                <div class="col-md-6">
                    <input id="EnterpriseContactnumber" type="number" class="form-control" name="EnterpriseContactnumber" value="{{ $enterprise->EnterpriseContactnumber }}" required autofocus>

                    @if ($errors->has('EnterpriseContactnumber'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseContactnumber') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('EnterpriseAddress') ? ' has-error' : '' }}">
                <label for="EnterpriseAddress" class="col-md-2 control-label">Company Address</label>

                <div class="col-md-6">
                    <input id="EnterpriseAddress" type="text" class="form-control" name="EnterpriseAddress" value="{{$enterprise->EnterpriseAddress}}" required autofocus>

                    @if ($errors->has('EnterpriseAddress'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseAddress') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('EnterpriseEmail') ? ' has-error' : '' }}">
                <label for="EnterpriseEmail" class="col-md-2 control-label">Email</label>

                <div class="col-md-6">
                    <input id="EnterpriseEmail" type="email" class="form-control" name="EnterpriseEmail" value="{{ $enterprise->EnterpriseEmail }}" required autofocus>

                    @if ($errors->has('EnterpriseEmail'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseEmail') }}</strong>
                                    </span>
                    @endif

                    <div class="modal-footer">
                        <button type="submit"  class="btn btn-primary">Save</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    </div>

                </div>
            </div>

        </div>

    </div>

</form>


</div>
    </section>
@endsection

resources/views/product/product.blade.php
@extends('layouts.admin_layout')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        View Product
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
    </ol>
</section>

<!-- Main content -->
<section style="background-color:white" class="content container-fluid">


        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <p>{{ $message }}</p>
            </div>
    @endif



                    <div class="col-sm-2" style="margin-top: 4%;margin-bottom: 2%">

                    </div>


        
        <table id="SMS" class="table table-bordered table-hover dataTable" role="grid">
            <thead>
            <tr role="row">
                <th>Number</th>
                <th >Product Name</th>
                <th>Category</th>
                <th>Status</th>
                <th >Description</th>
                <th >Original Price</th>
                <th >Discount Price</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($products as $product)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $product->name}}</td>
                <td>{{ $product->category_name}}</td>

                @if ($product -> isAvailable)
                    <td><span class="label label-primary">ACTIVE</span></td>
                @else
                <td><span class="label label-warning">INACTIVE</span></td>
                @endif

                <td>{{ $product->description}}</td>
                <td>{{ $product->original_price}}</td>
                <td>{{ $product->discount_price}}</td>
                <td>
                    <a href="{{ route('product.edit',$product->id) }}" class="btn btn-sm btn-primary"  title="Edit" ><i class="glyphicon glyphicon-pencil"></i> Edit  </a>

                @if ($product -> isAvailable)
                
                    <a href="{{ route('product.deactivate',$product->id) }}" class="btn btn-sm btn-success"  title="Reserve" ><i class="glyphicon glyphicoen-pencil"></i> Disable  </a>
                
                @else
                
                    <a href="{{ route('product.activate',$product->id) }}" class="btn btn-sm btn-success"  title="Reserve" ><i class="glyphicon glyphicoen-pencil"></i> Activate  </a>
                
                @endif
    
                </td>
            </tr>
            @endforeach

            </tbody>
        </table>



</section>


@endsection

@if ($errors->any())

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>

        $(function($) {

            $('#createEnterprise\n').click();
        })

    </script>

@endif