routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(array('prefix'=>'admin','middleware' => ['auth']), function ()
{
    Route::get('/', 'CategoryController@index');
    Route::get('/product/{id}/deactivate','ProductController@deactivate')->name('product.deactivate');
    Route::get('/product/{id}/activate','ProductController@activate')->name('product.activate');
    Route::resource('category','CategoryController');
    Route::resource('product','ProductController');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable = [
        'category_name',
    ];

    public function products()
    {
        return $this->hasMany('App\Product','category_id');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categories = Category::latest()->paginate(5);
        return view('category.category', compact('categories'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        request()->validate([
            'category_name' => 'required|unique:Categories',
        ]);

        Category::create($request->all());

        return redirect()->route('category.index')
            ->with('success', 'Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/category/add_category.blade.php
<div class="modal fade bs-modal-ce"  role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title">Category Form</h3>
            </div>
            <form class="form-horizontal" method="POST" action="{{ route('category.store')}}">
                {{ csrf_field() }}
                <div class="modal-body form">

                    <div class="form-body">

                        <div class="form-group{{ $errors->has('category_name') ? ' has-error' : '' }}">
                            <label for="category_name" class="col-md-4 control-label">Category Name</label>

                            <div class="col-md-6">
                                <input id="category_name" type="text" class="form-control" name="category_name" value="{{ old('category_name') }}" required autofocus>

                                @if ($errors->has('category_name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('category_name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                    </div>

                </div>
                <div class="modal-footer">


                    <button type="submit"  class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>

resources/views/category/category.blade.php
@extends('layouts.admin_layout')
@section('content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Category
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
    </ol>
</section>

<!-- Main content -->
<section style="background-color:white" class="content container-fluid">


        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-dismissable">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <p>{{ $message }}</p>
            </div>
    @endif



                    <div class="col-sm-2" style="margin-top: 4%;margin-bottom: 2%">
            <button id="createEnterprise" type="button"  class="btn btn-block btn-success " data-toggle="modal" data-target=".bs-modal-ce">
                <i class="glyphicon glyphicon-plus"></i>
                <b>&nbsp;&nbsp;CREATE</b>
            </button>

        </div>


        
        <table id="SMS" class="table table-bordered table-hover dataTable" role="grid">
            <thead>
            <tr role="row">
                <th>Number</th>
                <th >Category Id</th>
                <th>Category Name</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($categories as $category)
            <tr>
                <td>{{ ++$i }}</td>
                <td>{{ $category->id}}</td>
                <td>{{ $category->category_name}}</td>
                <td>
                    <a href="{{ route('category.edit',$category->id) }}" class="btn btn-sm btn-primary"  title="Edit" ><i class="glyphicon glyphicon-pencil"></i> Edit  </a>
                    <a href="{{ route('category.destroy',$category->id) }}" class="btn btn-sm btn-danger"  title="Reserve" ><i class="glyphicon glyphicoen-pencil"></i> Delete  </a>

                </td>
            </tr>
            @endforeach

            </tbody>
        </table>


    {!! $categories->links() !!}

</section>


@include('category.add_category')
@endsection

@if ($errors->any())

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>

        $(function($) {

            $('#createEnterprise\n').click();
        })

    </script>

@endif

resources/views/category/edit_category.blade.php
@extends('AdminLayout')
@section('content')

    <section class="content-header">
        <h1>
            Edit Category
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>

    <!-- Main content -->
    <section style="background-color:white" class="content container-fluid">

<div class="row">
            <div class="modal-header">
                {{--<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>--}}
                {{-- <h3 class="modal-title">Enterprise Form</h3>--}}
            </div>
<form  class="form-horizontal" method="POST" action="{{ route('enterprise.update',$enterprise->EnterpriseId) }}">
    <input type="hidden" name="_method" value="PUT">
    {{ csrf_field() }}
    <div class="modal-body edit-content form">


        <div class="form-body">

            <div class="form-group{{ $errors->has('EnterpriseName') ? ' has-error' : '' }}">
                <label for="EnterpriseName" class="col-md-2 control-label">Company Name</label>

                <div class="col-md-6">
                    <label  id="EnterpriseName" type="text" class="form-control" name="EnterpriseName">{{$enterprise->EnterpriseName}}</label>

                    @if ($errors->has('EnterpriseName'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseName') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('EnterpriseContactnumber') ? ' has-error' : '' }}">
                <label for="EnterpriseName" class="col-md-2 control-label">Contact Number</label>

                <div class="col-md-6">
                    <input id="EnterpriseContactnumber" type="number" class="form-control" name="EnterpriseContactnumber" value="{{ $enterprise->EnterpriseContactnumber }}" required autofocus>

                    @if ($errors->has('EnterpriseContactnumber'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseContactnumber') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('EnterpriseAddress') ? ' has-error' : '' }}">
                <label for="EnterpriseAddress" class="col-md-2 control-label">Company Address</label>

                <div class="col-md-6">
                    <input id="EnterpriseAddress" type="text" class="form-control" name="EnterpriseAddress" value="{{$enterprise->EnterpriseAddress}}" required autofocus>

                    @if ($errors->has('EnterpriseAddress'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseAddress') }}</strong>
                                    </span>
                    @endif
                </div>
            </div>

            <div class="form-group{{ $errors->has('EnterpriseEmail') ? ' has-error' : '' }}">
                <label for="EnterpriseEmail" class="col-md-2 control-label">Email</label>

                <div class="col-md-6">
                    <input id="EnterpriseEmail" type="email" class="form-control" name="EnterpriseEmail" value="{{ $enterprise->EnterpriseEmail }}" required autofocus>

                    @if ($errors->has('EnterpriseEmail'))
                        <span class="help-block">
                                        <strong>{{ $errors->first('EnterpriseEmail') }}</strong>
                                    </span>
                    @endif

                    <div class="modal-footer">
                        <button type="submit"  class="btn btn-primary">Save</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    </div>

                </div>
            </div>

        </div>

    </div>

</form>


</div>
    </section>
@endsection